# Generated by Django 4.2.24 on 2025-09-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("held", "Held"),
                            ("released", "Released"),
                            ("refunded", "Refunded"),
                        ],
                        default="held",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("held_by_platform", models.BooleanField(default=True)),
                (
                    "mpesa_receipt_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("buyer_phone", models.CharField(default="UNKNOWN", max_length=15)),
                ("artisan_phone", models.CharField(default="UNKNOWN", max_length=15)),
                (
                    "result_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("transaction_date", models.DateTimeField(blank=True, null=True)),
                (
                    "refunded_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
