# Generated by Django 4.2.24 on 2025-09-17 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="buyer_id",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "buyer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="order_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
        migrations.AddField(
            model_name="ordertracking",
            name="artisan_id",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "artisan"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ordertracking",
            name="order_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="artisan_id",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "artisan"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_artisan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="buyer_id",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "buyer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_buyer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="product_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.inventory",
            ),
        ),
        migrations.AddField(
            model_name="customdesignrequest",
            name="artisan_id",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "artisan"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_requests_as_artisan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customdesignrequest",
            name="buyer_id",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "buyer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_requests_as_buyer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("order_id", "buyer_id")},
        ),
    ]
